### ISSUE TITLE
Quick sound page

### ISSUE THREAD

**Issue by Noctabou** [Tom4nt/Mega-Soundboard#54]
Hello, i love your app (i think you know now)
I categorize my sounds by folder, like :
- sounds from streamers -> streamers
- sounds that are in french -> french
- sounds from Smash Bros -> SSBU
- ...

But sometimes, id like to have one of each in the same page. 
So i'd like a page where yo
u could maybe drag and drop a sound in, and it doesn't move the file itself.
I think like a cursor pointing the file entry into a new page called maybe "Quick Sounds".
![Sans titre1](https://github.com/Tom4nt/Mega-Soundboard/assets/54266662/768dfdfa-5c7a-4725-956b-f030ebb1f889)
![Sans titre2](https://github.com/Tom4nt/Mega-Soundboard/assets/54266662/fb474064-f220-4b6a-a236-949673da9b81)

**Comment by Tom4nt** [comment]
Thank you for your continuous contributions. I would like to clarify some things before thinking of how to implement this.
Fundamentally, what you want is a quick way to reference sounds in a new soundboard, am I right?

I say this because you can technically do this with the current version, by creating a new Soundboard and adding some sounds again. It's just very tedious and slow.
From what I understood, you suggested a new special type of soundboard, but maybe this can be implemented in a more general way for all soundboards. Like this:

- Sounds could be dragged to soundboards with the `CTRL` key pressed, which would copy[^1] the sound instead of moving it (just like in Windows).
- Sounds could be dragged to the "New Soundboard" button, creating a new regular Soundboard with some default name (maybe "Quick Sounds") and adding the sound to it. This could work with the `CTRL` key as well.
![image](https://github.com/Tom4nt/Mega-Soundboard/assets/39926566/f25daa90-e199-4b0f-a172-4388e94c7094)

Keep in mind that I'm not trying to disregard your suggestion, I'm just trying to simplify it to a point it can still be what you want, but also not too specific so other people can find it useful eventually.
Does this still satisfy your requirements? Please let me know.

[^1]: Copied sounds reference the same file, so it is never duplicated. It is possible to do this now if you add a new sound twice without checking "Move Sound". These sounds have independent settings: Name, Keybind, Volume. I don't know if this is what you want. If not, we could have some kind of "reference" type sound.

**Comment by Noctabou** [comment]
Oh yeah, your idea seems perfect. Easy, quick.
Also, i agree with the footnote, do not duplicate the file, it should be 2 entries pointing at the same file.
Your suggestion satisfy my requirements 👌

**Comment by Tom4nt** [comment]
Closed by 0092ecf1a08ef9934c52a28018248b0d95cb9d37
